name: Sync Fork with Upstream

on:
  schedule:
    # 15:00Z, every Wednesday
    - cron: "00 15 * * 3"
  workflow_dispatch: # or on button click

env:
  YOUR_REPO_PRIMARY_BRANCH_NAME: "main"

jobs:
  sync:
    if: github.repository != 'panther-labs/panther-analysis'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1
        id: set_upstream
        name: Check Upstream
        with:
          script: |
            const { data: { tag_name } } = await github.rest.repos.getLatestRelease({
              owner: 'panther-labs',
              repo: 'panther-analysis'
            });
            core.setOutput('latest-release', tag_name);
      ## CREATE A BRANCH
      - uses: peterjgrainger/action-create-branch@10c7d268152480ae859347db45dc69086cef1d9c #v3.0.0
        id: create_a_branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "sync_upstream_${{steps.set_upstream.outputs.latest-release}}"
      # Checkout this repo into the branch
      - name: Checkout your local repo in PR branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          ref: "sync_upstream_${{steps.set_upstream.outputs.latest-release}}"
          fetch-depth: 0
      # Sync this branch with upstream
      - name: Sync upstream changes into PR branch
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@1090e365224fc834e7e1de521c417ded2d6fcb53 #v3.4.1
        with:
          target_sync_branch: "sync_upstream_${{steps.set_upstream.outputs.latest-release}}"
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: "refs/tags/${{steps.set_upstream.outputs.latest-release}}"
          upstream_sync_repo: panther-labs/panther-analysis
          upstream_pull_args: "--allow-unrelated-histories"
          file_patterns: |
            !.github/**
            *
      - name: Create Pull Request
        if: steps.sync.outputs.has_new_commits == 'true'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1
        with:
          script: |
            try {
              const { data: pulls } = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: `${context.repo.owner}:sync_upstream_${{steps.set_upstream.outputs.latest-release}}`,
                state: 'open'
              });
              
              if (pulls.length === 0) {
                const { data: pr } = await github.rest.pulls.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: 'Sync with upstream repository',
                  head: `sync_upstream_${{steps.set_upstream.outputs.latest-release}}`,
                  base: 'main',
                  body: 'Automated PR to sync changes from upstream repository'
                });
                console.log(`Created PR: ${pr.html_url}`);
              } else {
                console.log('PR already exists');
              }
            } catch (error) {
              console.log(`Error creating PR: ${error}`);
              core.setFailed(error.message);
            }
